[project]
name = "fastapi-app"
version = "0.1.0"
description = "This is a FastAPI app."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pymongo>=4.10.1",
    "python-dotenv>=1.0.1",
]
